//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XFileStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XFileStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFile.XFileStrings", typeof(XFileStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current directory.
        /// </summary>
        internal static string ChangeDirectorySummary {
            get {
                return ResourceManager.GetString("ChangeDirectorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies files. Source can include filename wildcards. Destination is assumed to be the current directory if not specified. If the source is one file and the destination isn&apos;t an existing directory the destination is assumed to be the destination filename.
        ///
        ///copy source [destination] [/overwrite].
        /// </summary>
        internal static string CopyTaskHelp {
            get {
                return ResourceManager.GetString("CopyTaskHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite   (/ow)   Overwrite existing destination file.
        /// </summary>
        internal static string CopyTaskOptions {
            get {
                return ResourceManager.GetString("CopyTaskOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy a file to a given location.
        /// </summary>
        internal static string CopyTaskSummary {
            get {
                return ResourceManager.GetString("CopyTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List files in the current directory.
        /// </summary>
        internal static string DirectoryTaskSummary {
            get {
                return ResourceManager.GetString("DirectoryTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the device alias for the given volume or list all aliases.
        /// </summary>
        internal static string DosAliasTaskSummary {
            get {
                return ResourceManager.GetString("DosAliasTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo input.
        /// </summary>
        internal static string EchoTaskSummary {
            get {
                return ResourceManager.GetString("EchoTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target was specified..
        /// </summary>
        internal static string ErrorNoTargetSpecified {
            get {
                return ResourceManager.GetString("ErrorNoTargetSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command requires a source and a destination..
        /// </summary>
        internal static string ErrorRequiresSourceAndDestination {
            get {
                return ResourceManager.GetString("ErrorRequiresSourceAndDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command requires a target..
        /// </summary>
        internal static string ErrorRequiresTarget {
            get {
                return ResourceManager.GetString("ErrorRequiresTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List detailed file information.
        /// </summary>
        internal static string FileInfoTaskSummary {
            get {
                return ResourceManager.GetString("FileInfoTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the final (canonical) path.
        /// </summary>
        internal static string FinalPathTaskSummary {
            get {
                return ResourceManager.GetString("FinalPathTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the full (qualified) path.
        /// </summary>
        internal static string FullPathTaskSummary {
            get {
                return ResourceManager.GetString("FullPathTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XFile is a sample xTask based application..
        /// </summary>
        internal static string HelpGeneral {
            get {
                return ResourceManager.GetString("HelpGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List alternate streams for the given path.
        /// </summary>
        internal static string ListStreamsTaskSummary {
            get {
                return ResourceManager.GetString("ListStreamsTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List available drives.
        /// </summary>
        internal static string LogicalDriveStringsTaskSummary {
            get {
                return ResourceManager.GetString("LogicalDriveStringsTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the long name path.
        /// </summary>
        internal static string LongPathTaskSummary {
            get {
                return ResourceManager.GetString("LongPathTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the given directory.
        /// </summary>
        internal static string MakeDirectoryTaskSummary {
            get {
                return ResourceManager.GetString("MakeDirectoryTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the mount point for the given path.
        /// </summary>
        internal static string MountPointTaskSummary {
            get {
                return ResourceManager.GetString("MountPointTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current directory.
        /// </summary>
        internal static string PrintCurrentDirectoryTaskSummary {
            get {
                return ResourceManager.GetString("PrintCurrentDirectoryTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos; and all directories and files within?.
        /// </summary>
        internal static string QueryDeleteDirectory {
            get {
                return ResourceManager.GetString("QueryDeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the given directory.
        /// </summary>
        internal static string RemoveDirectoryTaskSummary {
            get {
                return ResourceManager.GetString("RemoveDirectoryTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the short name path.
        /// </summary>
        internal static string ShortPathTaskSummary {
            get {
                return ResourceManager.GetString("ShortPathTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the given file.
        /// </summary>
        internal static string TypeTaskSummary {
            get {
                return ResourceManager.GetString("TypeTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List information for the given volume.
        /// </summary>
        internal static string VolumeInformationTaskSummary {
            get {
                return ResourceManager.GetString("VolumeInformationTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the mount points for the given volume.
        /// </summary>
        internal static string VolumeMountPointsTaskSummary {
            get {
                return ResourceManager.GetString("VolumeMountPointsTaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the volume name for the given mount point.
        /// </summary>
        internal static string VolumeNameTaskSummary {
            get {
                return ResourceManager.GetString("VolumeNameTaskSummary", resourceCulture);
            }
        }
    }
}
