//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTask; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class XTaskStrings {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal XTaskStrings() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XTask.XTaskStrings", typeof(XTaskStrings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to File Path.
    /// </summary>
    internal static string ConfigurationLocationColumn {
        get {
            return ResourceManager.GetString("ConfigurationLocationColumn", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Configuration Type.
    /// </summary>
    internal static string ConfigurationTypeColumn {
        get {
            return ResourceManager.GetString("ConfigurationTypeColumn", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Could not find {0}..
    /// </summary>
    internal static string CouldNotFindGeneral {
        get {
            return ResourceManager.GetString("CouldNotFindGeneral", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} default properties
    ///.
    /// </summary>
    internal static string DefaultsCount {
        get {
            return ResourceManager.GetString("DefaultsCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Location.
    /// </summary>
    internal static string DefaultsLocationColumnHeader {
        get {
            return ResourceManager.GetString("DefaultsLocationColumnHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Removing default setting for {0}... .
    /// </summary>
    internal static string DefaultsRemovingProgress {
        get {
            return ResourceManager.GetString("DefaultsRemovingProgress", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Saving default setting for {0}... .
    /// </summary>
    internal static string DefaultsSavingProgress {
        get {
            return ResourceManager.GetString("DefaultsSavingProgress", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Setting.
    /// </summary>
    internal static string DefaultsSettingColumnHeader {
        get {
            return ResourceManager.GetString("DefaultsSettingColumnHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to List and set option defaults.
    /// </summary>
    internal static string DefaultsTaskSummary {
        get {
            return ResourceManager.GetString("DefaultsTaskSummary", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Default Value.
    /// </summary>
    internal static string DefaultsValueColumnHeader {
        get {
            return ResourceManager.GetString("DefaultsValueColumnHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;empty&gt;.
    /// </summary>
    internal static string EmptyString {
        get {
            return ResourceManager.GetString("EmptyString", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The argument &apos;{0}&apos; must have a value..
    /// </summary>
    internal static string ErrorArgumentMustHaveValue {
        get {
            return ResourceManager.GetString("ErrorArgumentMustHaveValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The directory &apos;{0}&apos; could not be found..
    /// </summary>
    internal static string ErrorDirectoryNotFound {
        get {
            return ResourceManager.GetString("ErrorDirectoryNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be found..
    /// </summary>
    internal static string ErrorFileNotFound {
        get {
            return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Error: {0}.
    /// </summary>
    internal static string ErrorFormatString {
        get {
            return ResourceManager.GetString("ErrorFormatString", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No parameters specified..
    /// </summary>
    internal static string ErrorNoParametersSpecified {
        get {
            return ResourceManager.GetString("ErrorNoParametersSpecified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;{0}&apos; is a file, not a directory..
    /// </summary>
    internal static string ErrorNotADirectory {
        get {
            return ResourceManager.GetString("ErrorNotADirectory", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;{0}&apos; is a directory, not a file..
    /// </summary>
    internal static string ErrorNotAFile {
        get {
            return ResourceManager.GetString("ErrorNotAFile", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The specified parameter file &apos;{0}&apos; is invalid..
    /// </summary>
    internal static string ErrorParameterFileInvalid {
        get {
            return ResourceManager.GetString("ErrorParameterFileInvalid", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to failed..
    /// </summary>
    internal static string Failed {
        get {
            return ResourceManager.GetString("Failed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This file is used to track abandoned temporary files..
    /// </summary>
    internal static string FlagFileContent {
        get {
            return ResourceManager.GetString("FlagFileContent", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Manages defaults for command options. Defaults have environment variables expanded when
    ///retrieved.
    ///
    ///{0} defaults [/list] [[/add]|[/remove]:{{location}} [[/{{option}}:{{value}}]...]].
    /// </summary>
    internal static string HelpDefaults {
        get {
            return ResourceManager.GetString("HelpDefaults", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to /list              Lists current default options and locations
    ////add               Adds all specified options
    ////remove            Removes all specified options
    ///
    ///Location must be one of the following:
    ///
    ///Local                Local user config
    ///Roaming              Roaming user config
    ///Executable           App.exe.config.
    /// </summary>
    internal static string HelpDefaultsOptions {
        get {
            return ResourceManager.GetString("HelpDefaultsOptions", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This program has no general help..
    /// </summary>
    internal static string HelpGeneral {
        get {
            return ResourceManager.GetString("HelpGeneral", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No help available for the specified command..
    /// </summary>
    internal static string HelpNone {
        get {
            return ResourceManager.GetString("HelpNone", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Option Details:.
    /// </summary>
    internal static string HelpOptionDetailHeader {
        get {
            return ResourceManager.GetString("HelpOptionDetailHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Start interactive mode.
    /// </summary>
    internal static string InteractiveTaskSummary {
        get {
            return ResourceManager.GetString("InteractiveTaskSummary", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;NONE&gt;.
    /// </summary>
    internal static string NoValue {
        get {
            return ResourceManager.GetString("NoValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;null&gt;.
    /// </summary>
    internal static string NullString {
        get {
            return ResourceManager.GetString("NullString", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Task.
    /// </summary>
    internal static string OverviewColumn1 {
        get {
            return ResourceManager.GetString("OverviewColumn1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Aliases.
    /// </summary>
    internal static string OverviewColumn2 {
        get {
            return ResourceManager.GetString("OverviewColumn2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Summary.
    /// </summary>
    internal static string OverviewColumn3 {
        get {
            return ResourceManager.GetString("OverviewColumn3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to succeeded..
    /// </summary>
    internal static string Succeeded {
        get {
            return ResourceManager.GetString("Succeeded", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The command specified &apos;{0}&apos; isn&apos;t recognized. Use &quot;help&quot; for a list of commands..
    /// </summary>
    internal static string UnknownCommand {
        get {
            return ResourceManager.GetString("UnknownCommand", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} [yes/no] .
    /// </summary>
    internal static string YesNoQueryStringFormat {
        get {
            return ResourceManager.GetString("YesNoQueryStringFormat", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to yes.
    /// </summary>
    internal static string YesResponse {
        get {
            return ResourceManager.GetString("YesResponse", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to y.
    /// </summary>
    internal static string YesShortResponse {
        get {
            return ResourceManager.GetString("YesShortResponse", resourceCulture);
        }
    }
}
