// ----------------------
//    xTask Framework
// ----------------------
// (This file was generated by the T4 template engine)

namespace XTask.Utility
{
    /// <summary>
    /// Auto generated constants
    /// </summary>
    internal static class AutoGeneratedConstants
    {
        public static class Integers
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const int CurrentYear =  2016;

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const int CurrentMonth = 5;

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const int CurrentDayOfMonth =  18;

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const int CurrentHour = 19;

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const int CurrentMinute = 16;
        }

        public static class Strings
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const string CurrentYear =  "2016";

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const string CurrentMonth = "5";

            /// <summary>
            /// Current month 01..12
            /// </summary>
            public const string CurrentTwoDigitMonth = "05";

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
            public const string CurrentDayOfMonth =  "18";

            /// <summary>
            /// Current two digit day of the month 01..31
            /// </summary>
            public const string CurrentTwoDigitDayOfMonth =  "18";

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
            public const string CurrentHour = "19";

            /// <summary>
            /// Current two digit hour from 00..23
            /// </summary>
            public const string CurrentTwoDigitHour = "19";

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
            public const string CurrentMinute = "16";

            /// <summary>
            /// Current two digit hour from 00..59
            /// </summary>
            public const string CurrentTwoDigitMinute = "16";
        }
    }
}
