// ----------------------
//    xTask Framework
// ----------------------
// (This file was generated by the T4 template engine)

namespace XTask.Utility
{
    /// <summary>
    /// Auto generated constants
    /// </summary>
    internal static class AutoGeneratedConstants
    {
        public static class Integers
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const int CurrentYear =  2015;

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const int CurrentMonth = 9;

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
<<<<<<< HEAD
            public const int CurrentDayOfMonth =  16;
=======
            public const int CurrentDayOfMonth =  1;
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
<<<<<<< HEAD
            public const int CurrentHour = 11;
=======
            public const int CurrentHour = 10;
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
<<<<<<< HEAD
            public const int CurrentMinute = 29;
=======
            public const int CurrentMinute = 32;
>>>>>>> Break out unknown task, add more unit tests.
        }

        public static class Strings
        {
            /// <summary>
            /// Current year
            /// </summary>
            public const string CurrentYear =  "2015";

            /// <summary>
            /// Current month 1..12
            /// </summary>
            public const string CurrentMonth = "9";

            /// <summary>
            /// Current month 01..12
            /// </summary>
            public const string CurrentTwoDigitMonth = "09";

            /// <summary>
            /// Current day of the month 1..31
            /// </summary>
<<<<<<< HEAD
            public const string CurrentDayOfMonth =  "16";
=======
            public const string CurrentDayOfMonth =  "1";
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current two digit day of the month 01..31
            /// </summary>
<<<<<<< HEAD
            public const string CurrentTwoDigitDayOfMonth =  "16";
=======
            public const string CurrentTwoDigitDayOfMonth =  "01";
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current hour from 0..23
            /// </summary>
<<<<<<< HEAD
            public const string CurrentHour = "11";
=======
            public const string CurrentHour = "10";
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current two digit hour from 00..23
            /// </summary>
<<<<<<< HEAD
            public const string CurrentTwoDigitHour = "11";
=======
            public const string CurrentTwoDigitHour = "10";
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current hour from 0..59
            /// </summary>
<<<<<<< HEAD
            public const string CurrentMinute = "29";
=======
            public const string CurrentMinute = "32";
>>>>>>> Break out unknown task, add more unit tests.

            /// <summary>
            /// Current two digit hour from 00..59
            /// </summary>
<<<<<<< HEAD
            public const string CurrentTwoDigitMinute = "29";
=======
            public const string CurrentTwoDigitMinute = "32";
>>>>>>> Break out unknown task, add more unit tests.
        }
    }
}
